# Generated by Django 5.0.6 on 2024-05-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_leaverequest_requested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteissue',
            name='supporting_document',
            field=models.FileField(default=1, upload_to='supporting_documents/'),
            preserve_default=False,
        ),
    ]
