# Generated by Django 5.0.6 on 2024-05-22 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_district_officelevel_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='siteissue',
            name='transfered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteissue',
            name='transferred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferred_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
