# Generated by Django 5.0.6 on 2024-05-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_siteissue_transfered_siteissue_transferred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='officelevel',
            name='office_level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteissue',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Transfered', 'Transfered')], default='Open', max_length=50),
        ),
    ]
