# Generated by Django 5.0.6 on 2024-05-23 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_province_district_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='province',
        ),
    ]
