# Generated by Django 5.0.6 on 2024-05-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_district_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cell',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
